version: '3'
services:
  client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  onchain-non-merklized-issuer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
