name: Publish
on:
  workflow_dispatch:

jobs:
  publish_onchain-non-merklized-issuer-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine tag
        id: tag
        run: |
          ref=$(echo ${{ github.ref }} | cut -d'/' -f3)
          echo "Original ref: $ref"
          if [[ "$ref" == "master" ]]; then
            echo "::set-output name=tag::latest"
          elif [[ "$ref" == "develop" ]]; then
            echo "::set-output name=tag::develop"
          else
            echo "::set-output name=tag::$ref"
          fi

      - name: Build and Deploy to ghcr.io
        run: |
          tag=${{ steps.tag.outputs.tag }}
          echo "Using tag: $tag"
          docker buildx build -f build/Dockerfile --push \
          --platform linux/amd64,linux/arm64 \
          -t ghcr.io/${{ github.repository }}:${tag} .